serviceExternalIp:
  name: node-exporter
  labels:
    app: node-exporter
  service:
    enabled: true
    ports:
      - name: "http"
        protocol: "TCP"
        port: "9100"
        targetPort: "9100"
      - name: "http-metrics"
        protocol: "TCP"
        port: "9187"
        targetPort: "9187"
    endpoints:
      ip: "192.168.56.101"
