# -*- mode: ruby -*-
# vi: set ft=ruby:

cpu = "4"
mem = "8196"
box = "dbudakov/centos-kernel"

# box = "centos/7"
# box = "ubuntu/bionic64"
name_host = "terraform"
network = '192.168.56.101'
network_vlan = "private_network"

Vagrant.configure("2") do |config|
        config.vm.define "os" do |os|
                os.vm.box = box
                os.vm.host_name = name_host
                os.vm.network  network_vlan, ip: network
                os.vm.provider :virtualbox do |vb|
                        vb.name = name_host
                        vb.customize ["modifyvm", :id, "--memory", mem]
                        vb.customize ["modifyvm", :id, "--cpus", cpu]
                end
        end
        config.vm.synced_folder "./share", "/vagrant"
        config.vm.provision "file", source: "env/.bashrc", destination: "/tmp/.bashrc"
        config.vm.provision "shell", inline: "mv -f /tmp/.bashrc /root/.bashrc"
        config.vm.provision "shell", path: "scripts/promstack.sh"
        config.vm.provision  "shell", inline: <<-SHELL
                #...
        SHELL
end
