{
 "title": "PostgreSQL Query Drill-Down",
 "description": "PostgreSQL Query Drill-Down ",
 "tags": [
  "Percona",
  "PostgreSQL"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "host", "label": "Host", "query": "label_values(pg_up,instance)" },
   {
    "name": "queryid",
    "label": "Query ID",
    "query": "label_values(pg_stat_statements_calls{instance=\"$host\",datname!~\"template.*\"},queryid)"
   },
   {
    "name": "query",
    "label": "Query",
    "query": "label_values(pg_stat_statements_calls{queryid=\"$queryid\"},query)"
   }
  ]
 },
 "panels": [
  {
   "title": "Quiery $queryid",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<font color=#5991A7><b><center>$query</center></b></font>"
  },
  {
   "title": "Query Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_calls{instance=\"$host\",queryid=~\"$queryid\"}[$interval]) or \nirate(pg_stat_statements_calls{instance=\"$host\",queryid=~\"$queryid\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_time_milliseconds{instance=~\"$host\",queryid=~\"$queryid\"}[$interval]) or\nirate(pg_stat_statements_time_milliseconds{instance=~\"$host\",queryid=~\"$queryid\"}[5m])) by (datname, queryid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Query Time per Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_time_milliseconds{instance=~\"$host\",queryid=~\"$queryid\"}[$interval]) / \n(rate(pg_stat_statements_calls{instance=~\"$host\",queryid=~\"$queryid\"}[$interval]) > 0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Retrieved or Affected  Rows",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_rows{instance=~\"$host\",queryid=~\"$queryid\"}[$interval])) by (queryid, datname)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rows Processed per Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_rows{instance=~\"$host\",queryid=~\"$queryid\"}[$interval]) / \nrate(pg_stat_statements_calls{instance=~\"$host\",queryid=~\"$queryid\"}[$interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shared Blocks Read",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_shared_blks_read{instance=~\"$host\",queryid=~\"$queryid\"}[5m])) by (queryid, datname)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shared Blocks Read per Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_shared_blks_read{instance=~\"$host\",queryid=\"$queryid\"}[5m]) * 8 / \nrate(pg_stat_statements_calls{instance=~\"$host\",queryid=~\"$queryid\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Local Blocks Read",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_local_blks_read{instance=~\"$host\",queryid=~\"$queryid\"}[5m])) by (queryid, datname)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Local Blocks Read per Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_local_blks_read{instance=~\"$host\",queryid=\"$queryid\"}[5m]) * 8 / \nrate(pg_stat_statements_calls{instance=~\"$host\",queryid=~\"$queryid\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shared Blocks Written",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_shared_blks_written{instance=~\"$host\",queryid=~\"$queryid\"}[$interval])) by (queryid, datname)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shared Blocks Written per Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_shared_blks_written{instance=~\"$host\",queryid=~\"$queryid\"}[$interval]) / \nrate(pg_stat_statements_calls{instance=~\"$host\",queryid=~\"$queryid\"}[$interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Local Blocks Written",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_local_blks_written{instance=~\"$host\",queryid=~\"$queryid\"}[$interval])) by (queryid, datname)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Local Blocks Written per Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_local_blks_written{instance=~\"$host\",queryid=~\"$queryid\"}[$interval]) / \nrate(pg_stat_statements_calls{instance=~\"$host\",queryid=~\"$queryid\"}[$interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shared Blocks Dirtied",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_shared_blks_dirtied{instance=~\"$host\",queryid=~\"$queryid\"}[$interval])) by (queryid, datname)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shared Blocks Dirtied per Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_shared_blks_dirtied{instance=~\"$host\",queryid=~\"$queryid\"}[$interval]) / \nrate(pg_stat_statements_calls{instance=~\"$host\",queryid=~\"$queryid\"}[$interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Local Blocks Dirtied",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_local_blks_dirtied{instance=~\"$host\",queryid=~\"$queryid\"}[$interval])) by (queryid, datname)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Local Blocks Dirtied per Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_local_blks_dirtied{instance=~\"$host\",queryid=~\"$queryid\"}[$interval]) / \nrate(pg_stat_statements_calls{instance=~\"$host\",queryid=~\"$queryid\"}[$interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shared Blocks Cache Hits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_shared_blks_hit{instance=~\"$host\",queryid=~\"$queryid\"}[$interval])) by (queryid, datname)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shared Blocks Cache Hits per Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_shared_blks_hit{instance=~\"$host\",queryid=~\"$queryid\"}[$interval]) / \nrate(pg_stat_statements_calls{instance=~\"$host\",queryid=~\"$queryid\"}[$interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Local Blocks Cache Hits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_local_blks_hit{instance=~\"$host\",queryid=~\"$queryid\"}[$interval])) by (queryid, datname)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Local Blocks Cache Hits per Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_local_blks_hit{instance=~\"$host\",queryid=~\"$queryid\"}[$interval]) / \nrate(pg_stat_statements_calls{instance=~\"$host\",queryid=~\"$queryid\"}[$interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temp Blocks I/O",
   "type": "graph",
   "description": "Data written through shared buffers (tables, indexes, etc.)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_temp_blks_read{instance=~\"$host\",queryid=~\"$queryid\"}[$interval])) by (queryid, datname)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}} - Read",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(rate(pg_stat_statements_temp_blks_written{instance=~\"$host\",queryid=~\"$queryid\"}[$interval])) by (queryid, datname)",
     "legendFormat": "{{queryid}} - {{datname}} - Written"
    }
   ]
  },
  {
   "title": "Temp Blocks I/O per Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_temp_blks_read{instance=~\"$host\",queryid=~\"$queryid\"}[$interval]) / \nrate(pg_stat_statements_calls{instance=~\"$host\",queryid=~\"$queryid\"}[$interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}} - Read",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(pg_stat_statements_temp_blks_written{instance=~\"$host\",queryid=~\"$queryid\"}[$interval]) / \nrate(pg_stat_statements_calls{instance=~\"$host\",queryid=\"~$queryid\"}[$interval])",
     "legendFormat": "{{queryid}} - {{datname}} - Written"
    }
   ]
  }
 ]
}